name: Deploy Astro site to Pages

on:
  push:
    branches: ["master"] # 确保你的分支名是 main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24" # 直接用最新的，消灭警告

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9 # 或者更高

      - name: Install dependencies
        run: pnpm install

      - name: Build with Astro
        run: pnpm run build --site "https://jellyfaith.github.io" --base "/"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
